project:
  type: website
  output-dir: docs
  
website:
  title: "Philanthropic Giving Analysis"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: Data Exploration
        menu:
          - text: eo1 data
            href: ./reports/data_exploration_ex.html
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        href: https://github.com/TheUndivideProject

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true