project:
  type: website
  output-dir: ../docs

website:
  title: "Philanthropic Giving Analysis"
  navbar:
    left:
      - text: Home
        href: index.html
      - text: Data Exploration
        menu:
          - text: Exempt Organizations Business Master File Data
            href: data_exploration/data_exploration_ex.html
    right:
      - icon: twitter
        href: http://linktr.ee/theundivide
      - icon: github
        href: https://github.com/TheUndivideProject
        aria-label: GitHub

  page-footer:
    right: |
      Made with [Quarto](https://quarto.org/)<br>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


